platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.0'
pod 'SVProgressHUD', '~> 1.0'
pod 'ICViewPager'
pod 'PEPhotoCropEditor'
pod 'MWPhotoBrowser'
pod 'REMenu','~> 1.10'
pod 'REFrostedViewController', '~> 2.4.7'
pod 'FMDB'
pod 'UMengAnalytics'
pod 'pop', '~> 1.0.7'
pod 'MMDrawerController'
